name: threat-detection-ai
true:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: threat-detection-ai
        auto-activate-base: false
        environment-file: .github/workflows/environment.yml
    - name: Install dependencies
      run: 'conda activate threat-detection-ai

        pip install -e .

        '
    - name: Run Tests
      run: 'conda activate threat-detection-ai

        pytest tests/

        '
  docker:
    name: Build and Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Build and tag Docker image
      run: 'docker build -t ${{ secrets.DOCKER_USERNAME }}/threat-detection-ai:latest
        .

        '
    - name: Push Docker image
      run: 'docker push ${{ secrets.DOCKER_USERNAME }}/threat-detection-ai:latest

        '
channels:
- defaults
- conda-forge
dependencies:
- python=3.10
- pip
- pandas
- numpy
- scikit-learn
- matplotlib
- seaborn
- jupyter
- notebook
- ipykernel
- pip:
  - xgboost
  - fastapi
  - uvicorn
  - joblib
  - prometheus-client
