name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: threat-detection-ai
        auto-activate-base: false

    - name: Verify environment setup
      run: conda info

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV # Also add root for test discovery

    - name: Run tests in environment
      shell: bash -l {0}
      run: |
        conda activate threat-detection-ai
        # PYTHONPATH is already set by the previous step via GITHUB_ENV
        python -m unittest discover tests/